---
spring:
  profiles: prod
server:
  port: 2222
  
datasource:
  pbmvc:
    url: jdbc:postgresql://localhost:5432/pbmvc
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
