---
spring:
  profiles:
    active: dev
  model-scan: com.bim.server
  http:
    multipart:
      max-file-size: 5120Mb
      max-request-size: 5120Mb

---
attachment:
  path: WEB-INF\classes\attachments\