debug: true

server:
  port: 1111
 
spring:
  aop:
    proxy-target-class: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


    multipart:
      enabled: true
      max-file-size: 256MB
      max-request-size: 256MB
      resolve-lazily: true      

security:
  user:
    password: password
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
#      scope: openid
    resource:
#      jwt:
#        keyValue: |
#          -----BEGIN PUBLIC KEY-----
#          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
#          -----END PUBLIC KEY-----
#      id: openid
      userInfoUri: http://localhost:9999/uaa/user
#      preferTokenInfo: false

zuul:
  routes:
    user:
      path: /user/**
      url: http://localhost:1111
    ui:
      path: /ui/**
      url: http://localhost:1111
      sensitiveHeaders: Cookie,Set-Cookie
    resource:
      path: /resource/**
      url: http://localhost:1111
      sensitiveHeaders: Cookie,Set-Cookie
    server:
      path: /server/**
      url: http://localhost:1111
      sensitiveHeaders: Cookie,Set-Cookie
    bimserverwar:
      path: /bimserverwar/**
      url: http://localhost:1111
      sensitiveHeaders: Cookie,Set-Cookie
    redsun:
      path: /redsun/**
      url: http://localhost:1111
    redsun-service:
      path: /redsun-service/**
      url: http://localhost:1111
    springmvc:
      path: /springmvc/**
      url: http://localhost:1111

ribbon:
  eureka:
    enabled: false
  ConnectTimeout: 30000
  ReadTimeout: 3600000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3600000

logging:
  level:
    org.springframework.security: DEBUG